### ISSUE TITLE
Зачем выкладывать в открытый доступ решения?

### ISSUE THREAD

**Issue by strangeronline** [NikiforovAll/codewars-playground#1]
Это не красивый поступок. Теперь те, кто выполнил задания честно будут конкурировать с теми, кто их закопипастил. Закройте, пожалуйста, доступ к этому репозитарию. Хвастать надо не решениями, а например транслейтами.  https://www.codewars.com/users/smartwinners

**Comment by NikiforovAll** [comment]
@strangeronline. Могли ли бы привести соответствующие правила платформы? Понимаю вашу позицию. 

 Я не преследую цель "похвастаться решением", репозиторий использую как базу знаний и способ синхронизации.

**Comment by strangeronline** [comment]
Я написал, что считаю такой поступок некрасивым и попросил закрыть репозиторий для всеобщего обозрения. Теряется  смысл в рейтингах, достаточно найти чей-нибудь репозитарий. Вы по прежнему сможете с ним работать.  Да и замените сказанное мною сгоряча слово "хвастать" на "публиковать". Приношу свои извинения за резкость.
